" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
set encoding=utf-8 " Necessary to show Unicode glyphs

" Reload vimrc on save
"autocmd! bufwritepost .vimrc source %

" ----------------------------------------------------------------------------
"  Plugins
" ----------------------------------------------------------------------------
" Managed by Vim's built-in package support (:help packages), not a plugin
" manager. Each plugin is a git submodule under
"   ~/.vim/pack/plugins/start/
" so versions are pinned by this repo. Add one with:
"   git submodule add --depth 1 https://github.com/<owner>/<repo>.git \
"       .vim/pack/plugins/start/<repo>
" then `make vim-helptags`. Update them all with `make vim-update`.
"
" Current set: nerdtree, nerdcommenter, ctrlp.vim, vim-airline, vim-solarized8,
" vim-surround, vim-gitgutter, ale, vim-go, typescript-vim, bufexplorer,
" vim-fugitive.
"
" ORDER MATTERS BELOW. Plugins in pack/*/start/ are not loaded while this file
" is being sourced -- Vim loads them immediately afterwards. So:
"   * plugin configuration (g:* variables) must be set BEFORE :packloadall
"   * anything that needs a plugin present (e.g. :colorscheme from a plugin)
"     must come AFTER :packloadall
" Note :packadd! cannot be used as a shortcut here -- it only searches
" pack/*/opt/, not pack/*/start/.

" ----------------------------------------------------------------------------
"  Plugin configuration (must precede :packloadall)
" ----------------------------------------------------------------------------

" Leader key. This MUST be set before :packloadall, not down in the mappings
" section: plugins that create default mappings (NERDCommenter's <leader>c*,
" for one) expand <leader> at load time. Set it afterwards and they silently
" bind to the default '\' instead, breaking the <leader><Space> map below.
let mapleader = ","

" NERDTree / NERDCommenter
let g:NERDAltDelims_javascript = 2
let NERDTreeShowHidden = 1
let NERDTreeIgnore = ['\.pyc$', '__pycache__[[dir]]']

" CtrlP -- max number of mru entries; too large and it gets slow to load
let g:ctrlp_map = ',e'
let g:ctrlp_mruf_max = 50

" Asynchronous Lint Engine (ALE)
" Limit linters used for JavaScript.
let g:ale_linters = {
\  'javascript': ['flow', 'eslint'],
\}
let g:ale_sign_error = 'X' " could use emoji
let g:ale_sign_warning = '?' " could use emoji
let g:ale_statusline_format = ['X %d', '? %d', '']
" %linter% is the name of the linter that provided the message
" %s is the error or warning message
let g:ale_echo_msg_format = '%linter% says %s'
" Map keys to navigate between lines with errors and warnings.
nnoremap <leader>an :ALENextWrap<cr>
nnoremap <leader>ap :ALEPreviousWrap<cr>

" allow plugins by file type
filetype plugin indent on  " load filetype plugin

" ----------------------------------------------------------------------------
"  Load plugins
" ----------------------------------------------------------------------------
" Everything above this line is plugin *configuration*; everything that needs a
" plugin to already be present goes below it. Vim would run this itself just
" after sourcing this file -- doing it explicitly lets the colorscheme (which
" ships in a plugin) be set here rather than deferred to VimEnter. Calling it
" twice is harmless: Vim only loads packages once.
packloadall

" :help tags for the plugins are generated by `make vim-helptags` rather than
" here -- running helptags on every startup rewrites a tags file in each
" plugin's doc/ directory for no benefit.

set whichwrap+=<,>,h,l

set cursorline
" Set to auto read when a file is changed from the outside
set spell
set autoread
" Disable backupfiles
set nobackup
set nowritebackup
set noswapfile

set wildignore+=*/.git/*,*/.DS_Store,*/node_modules/*

set history=700
set gdefault


" ----------------------------------------------------------------------------
"  Mappings
" ----------------------------------------------------------------------------

" <Leader> is set in the plugin configuration section above -- it has to be in
" place before plugins load.

" Fast saving
nmap <leader>w :w!<cr>

" Map space to / (search)
map - /
map ' /

" Exit insert mode without ESC
imap <C-c> <esc>

" Console ergonomics
map ö :
map ; :

set backspace=indent,eol,start

" Quick navigation
map <C-l> $
map <C-h> 0

" Search across the project with ripgrep via the built-in :grep.
" Replaces rking/ag.vim, which is archived upstream (and `ag` was not even
" installed here, so <leader>a had been silently broken).
" Prefer ripgrep (brew install ripgrep). Falls back to a recursive grep so the
" mapping below works either way -- Vim's default grepprg is
" `grep -n $* /dev/null`, which searches no files at all when given only a
" pattern, so a fallback is required, not optional.
if executable('rg')
  set grepprg=rg\ --vimgrep\ --smart-case\ --hidden\ --glob\ '!.git'
  set grepformat=%f:%l:%c:%m
else
  set grepprg=grep\ -rn\ --exclude-dir=.git\ --exclude-dir=node_modules\ $*\ .
endif
" Type the pattern, then <CR>; results land in the quickfix window.
map <leader>a <Esc>:grep! ""<Left>
" Jump through matches
nnoremap <leader>j :cnext<CR>
nnoremap <leader>k :cprevious<CR>
" Open quickfix automatically after a grep
autocmd QuickFixCmdPost grep,grepadd cwindow

" ----------------------------------------------------------------------------
" NerdTools
" ----------------------------------------------------------------------------
" Settings for these live in the plugin configuration section at the top --
" they have to be set before :packloadall.
map <leader><Space> <leader>c<Space>
map <silent> <leader>n :NERDTreeToggle<CR>
" Find current file in NerdTree
map <silent> <leader>N :NERDTreeFind<CR>

" ----------------------------------------------------------------------------
" CtrlP (fuzzy finder)
" ----------------------------------------------------------------------------
"nmap <leader>g :CtrlPBufTag<CR>
"nmap <leader>G :CtrlPBufTagAll<CR>
"nmap <leader>f :CtrlPLine<CR>
nmap <leader>f :CtrlPBuffer<CR>
nmap <leader>m :CtrlPMRUFiles<CR>

"
" Buffers
"
"map <leader>v :bnext<CR>
"map <leader>c :bprevious<CR>
map <leader>b :BufExplorer<CR>


"let g:BufferListWidth = 25
"let g:BufferListMaxWidth = 50
"hi BufferSelected term=reverse ctermfg=white ctermbg=red cterm=bold
"hi BufferNormal term=NONE ctermfg=black ctermbg=darkcyan cterm=NONE



" ----------------------------------------------------------------------------
" Vim-go
" ----------------------------------------------------------------------------
let g:go_fmt_autosave = 1
let g:go_fmt_command = "goimports"
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1

" ----------------------------------------------------------------------------
"  Text Formatting
" ----------------------------------------------------------------------------

set expandtab              " expand tabs to spaces
set softtabstop=2
set shiftwidth=4           " distance to shift lines with < and >
set tabstop=4                   " tab character display size
set smarttab

set lbr
set tw=500

set autoindent "Auto indent
set smartindent "Smart indent
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType javascript setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType typescript setlocal ts=2 sts=2 sw=2 expandtab
"set wrap "Wrap lines
" ----------------------------------------------------------------------------
"  Visual Cues
" ----------------------------------------------------------------------------

syntax on                  " enable syntax highlighting
let loaded_matchparen=1    " don't hightlight matching brackets/braces
set laststatus=2           " always show the status line
set hlsearch               " highlight all search terms
set incsearch              " highlight search text as entered
set ignorecase             " ignore case when searching
set smartcase              " case sensitive only if capitals in search term
set colorcolumn=80        " not available until Vim 7.3
set visualbell             " shut the
set showmatch
set number
set cursorline

" CursorLine/Cursor highlights are set in the Graphical section below, after
" :colorscheme -- setting them here would just be overwritten.

" Hightlight colum 120 and beyond
"let &colorcolumn="80,".join(range(120,999),",")
"
" Highlight trailing whitespace
"hi ExtraWhitespace ctermbg=darkgreen guibg=#A30008
"match ExtraWhitespace /\s\+\%#\@<!$/
" ----------------------------------------------------------------------------
"  Graphical
" ----------------------------------------------------------------------------
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)

"solarized if you use "set termguicolors".
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors

"let g:solarized_termcolors=256
" Works because :packloadall above has already put vim-solarized8 on the
" runtimepath. Without that, this would fail on startup.
colorscheme solarized8
set background=dark

" Highlight overrides. These must come after :colorscheme, which resets every
" highlight group -- and after :packloadall, since ALE defines these groups
" when it loads. Previously they sat near the top of this file and were
" silently overwritten by both.
highlight clear ALEErrorSign   " otherwise uses error bg color (typically red)
highlight clear ALEWarningSign " otherwise uses error bg color (typically red)
hi CursorLine term=bold cterm=bold guibg=Grey40
hi Cursor guibg=#0087ad


let s:uname = system("uname")
if s:uname == "Darwin\n"
  set guifont=Inconsolata\ for\ Powerline:h15
else                         " on Ubunt
  set guifont=Monospace\
endif

" ----------------------------------------------------------------------------
"  Slime
" ----------------------------------------------------------------------------
"let g:slime_target = "tmux"
"xmap <leader>s <Plug>SlimeRegionSend
"nmap <leader>s <Plug>SlimeParagraphSend
